# Config for multi-device full finetuning in full_finetune_distributed.py
# using a Qwen2.5 1.5B model
#
# This config assumes that you've run the following command before launching:
#   tune download Qwen/Qwen2.5-1.5B-Instruct --output-dir /tmp/Qwen2.5-1.5B-Instruct
#
# To launch on 2 devices, run the following command from root:
#   tune run --nproc_per_node 2 full_finetune_distributed --config qwen2_5/1.5B_full
#
# You can add specific overrides through the command line. For example
# to override the checkpointer directory while launching training:
#   tune run --nproc_per_node 2 full_finetune_distributed --config qwen2_5/1.5B_full checkpointer.checkpoint_dir=<YOUR_CHECKPOINT_DIR>
#
# This config is for fine-tuning on 2+ GPUs.

output_dir: /workspace/qwen-72b-r1-distill # /tmp may be deleted by your system. Change it to your preference.

# Model arguments
model:
  _component_: torchtune.models.qwen2_5.qwen2_5_72b_instruct

# Tokenizer
tokenizer:
  _component_: torchtune.models.qwen2_5.qwen2_5_tokenizer
  path: /workspace/qwen-72b-math/vocab.json
  merges_file: /workspace/qwen-72b-math/merges.txt
  max_seq_len: 20000

# Checkpointer
checkpointer:
  _component_: torchtune.training.FullModelHFCheckpointer
  checkpoint_dir: /workspace/qwen-72b-math
  checkpoint_files: [
    model-00001-of-00037.safetensors,
    model-00002-of-00037.safetensors,
    model-00003-of-00037.safetensors,
    model-00004-of-00037.safetensors,
    model-00005-of-00037.safetensors,
    model-00006-of-00037.safetensors,
    model-00007-of-00037.safetensors,
    model-00008-of-00037.safetensors,
    model-00009-of-00037.safetensors,
    model-00010-of-00037.safetensors,
    model-00011-of-00037.safetensors,
    model-00012-of-00037.safetensors,
    model-00013-of-00037.safetensors,
    model-00014-of-00037.safetensors,
    model-00015-of-00037.safetensors,
    model-00016-of-00037.safetensors,
    model-00017-of-00037.safetensors,
    model-00018-of-00037.safetensors,
    model-00019-of-00037.safetensors,
    model-00020-of-00037.safetensors,
    model-00021-of-00037.safetensors,
    model-00022-of-00037.safetensors,
    model-00023-of-00037.safetensors,
    model-00024-of-00037.safetensors,
    model-00025-of-00037.safetensors,
    model-00026-of-00037.safetensors,
    model-00027-of-00037.safetensors,
    model-00028-of-00037.safetensors,
    model-00029-of-00037.safetensors,
    model-00030-of-00037.safetensors,
    model-00031-of-00037.safetensors,
    model-00032-of-00037.safetensors,
    model-00033-of-00037.safetensors,
    model-00034-of-00037.safetensors,
    model-00035-of-00037.safetensors,
    model-00036-of-00037.safetensors,
    model-00037-of-00037.safetensors,
  ]
  recipe_checkpoint: null
  output_dir: ${output_dir}
  model_type: QWEN2
resume_from_checkpoint: False

# Dataset
dataset:
  _component_: torchtune.datasets.chat_dataset
  source: justus27/reasoning-test-4
  conversation_column: messages
  conversation_style: openai
  split: train
  packed: False  # True increases speed
seed: null
shuffle: True

# Fine-tuning arguments
epochs: 5
max_steps_per_epoch: null
fsdp_cpu_offload: True
batch_size: 1
gradient_accumulation_steps: 1  # Use to increase effective batch size
optimizer:
  _component_: torch.optim.AdamW
  fused: True
  lr: 4e-5
  offload_gradients: True
optimizer_in_bwd: True  # True saves memory. Requires gradient_accumulation_steps=1
loss:
  _component_: torchtune.modules.loss.CEWithChunkedOutputLoss

metric_logger:
  _component_: torchtune.training.metric_logging.WandBLogger
  project: torchtune

# Training env
device: cuda

# Memory management / performance
enable_activation_checkpointing: True  # True reduces memory
enable_activation_offloading: True  # True reduces memory
dtype: bf16
clip_grad_norm: null
compile: False  # torch.compile the model + loss, True increases speed + decreases memory

log_every_n_steps: 1
log_peak_memory_stats: True


# Profiler (disabled)
profiler:
  _component_: torchtune.training.setup_torch_profiler
  enabled: False

  #Output directory of trace artifacts
  output_dir: ${output_dir}/profiling_outputs

  #`torch.profiler.ProfilerActivity` types to trace
  cpu: True
  cuda: True

  #trace options passed to `torch.profiler.profile`
  profile_memory: False
  with_stack: False
  record_shapes: True
  with_flops: False

  # `torch.profiler.schedule` options:
  # wait_steps -> wait, warmup_steps -> warmup, active_steps -> active, num_cycles -> repeat
  wait_steps: 5
  warmup_steps: 3
  active_steps: 2
  num_cycles: 1
